//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace FuzzyMonkBlog.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Post
    {
        public Post()
        {
            this.Comment = new HashSet<Comment>();
        }
    
        public int Id { get; set; }
        public string Title { get; set; }
        public string Description { get; set; }
        public System.DateTime PostedDate { get; set; }
        public int WriterId { get; set; }
        public bool IsPublished { get; set; }
        public int NoOfView { get; set; }
    
        public virtual ICollection<Comment> Comment { get; set; }
        public virtual User User { get; set; }
    }
}
